### ISSUE TITLE
Javis version update

### ISSUE THREAD

**Issue by TheCutestCat** [divelab/AIRS#17]
Error happen for the model PotNet

for the version jarvis-tools-2022.9.16, we will meet an error when running 
** from jarvis.db.figshare import data
dft_3d = data(dataset='dft_3d')** 

Update to the latest version **jarvis-tools-2024.4.10** will solve it

**Error info :** 
 Obtaining 3D dataset 55k ...
Reference:https://www.nature.com/articles/s41524-020-00440-1
Loading the zipfile...
Traceback (most recent call last):
  File "/home/workspace/AIRS/OpenMat/PotNet/main.py", line 23, in <module>
    train_prop_model(data, data_root=args.data_root, checkpoint=args.checkpoint, testing=args.testing)
  File "/home/workspace/AIRS/OpenMat/PotNet/train_prop.py", line 479, in train_prop_model
    result = train_pyg(config, data_root=data_root, file_format=file_format, checkpoint=checkpoint, testing=testing)
  File "/home/workspace/AIRS/OpenMat/PotNet/train_prop.py", line 208, in train_pyg
    ) = get_train_val_loaders(
  File "/home/workspace/AIRS/OpenMat/PotNet/data.py", line 507, in get_train_val_loaders
    d = jdata(dataset)
  File "/home/anaconda3/envs/potnet/lib/python3.9/site-packages/jarvis/db/figshare.py", line 350, in data
    dat = get_request_data(js_tag=js_tag, url=url)
  File "/home/anaconda3/envs/potnet/lib/python3.9/site-packages/jarvis/db/figshare.py", line 303, in get_request_data
    data = json.loads(zipfile.ZipFile(path).read(js_tag))
  File "/home/anaconda3/envs/potnet/lib/python3.9/zipfile.py", line 1268, in __init__
    self._RealGetContents()
  File "/home/anaconda3/envs/potnet/lib/python3.9/zipfile.py", line 1335, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by KruskalLin** [comment]
Hi, I came across this issue before. It happens if your zip is not downloaded completely and you stop it halfway. Can you give it one more shot in the 2022 version of JARVIS?

Just a reminder, you can use the 2024 version as it fits the codes. However, the evaluation results will be better than we report as they include more data.
