### ISSUE TITLE
coformer代码运行不起来

### ISSUE THREAD

**Issue by qwertyuiopasdfghjklzxcn** [divelab/AIRS#21]
(chatglm2) E:\AIRS-main\OpenMat\ComFormer\comformer\scripts>python train_mp.py
INFO: Pandarallel will run on 8 workers.
INFO: Pandarallel will use standard multiprocessing data transfer (pipe) to transfer data between the main process and workers.

WARNING: You are on Windows. If you detect any issue with pandarallel, be sure you checked out the Troubleshooting page:
https://nalepae.github.io/pandarallel/troubleshooting/
Traceback (most recent call last):
  File "train_mp.py", line 7, in <module>
    from comformer.train_props import train_prop_model
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\23968\Anaconda3\envs\chatglm2\lib\site-packages\comformer-2024.6.5-py3.8.egg\comformer\train_props.py", line 7, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\23968\Anaconda3\envs\chatglm2\lib\site-packages\comformer-2024.6.5-py3.8.egg\comformer\train.py", line 40, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\23968\Anaconda3\envs\chatglm2\lib\site-packages\comformer-2024.6.5-py3.8.egg\comformer\config.py", line 12, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\23968\Anaconda3\envs\chatglm2\lib\site-packages\comformer-2024.6.5-py3.8.egg\comformer\models\comformer.py", line 14, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\23968\Anaconda3\envs\chatglm2\lib\site-packages\comformer-2024.6.5-py3.8.egg\comformer\models\transformer.py", line 13, in <module>
ModuleNotFoundError: No module named 'comforemr'

**Comment by YKQ98** [comment]
import sys
sys.path.append("/yourpath/comformer")

Have you adjust this accordingly?
